[tool.poetry]
name = "skcausal"
version = "0.1.0"
description = ""
authors = ["Felipe Angelim <felipeangelim@gmail.com>"]
license = "MIT"
readme = "README.md"
# Include cte directory inside src
packages = [{ from="src", include = "skcausal" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pandas = "^2.0.3"
scikit-learn = "^1.3.0"
torch = "^2.4.1"
jupyterlab = "^4.0.3"
matplotlib = "^3.7.2"
causal-curve = "^1.0.6"
tqdm = "^4.66.2"
ipywidgets = "^8.1.2"
jax = "^0.4.30"
flax = "^0.8.5"
skorch = "^1.0.0"
numpy = "<2.0"
skbase = "^0.4.6"
rich = "^13.7.1"
jupyter-client = "<8"
ipykernel = "^6.29.5"
click = "^8.1.7"
altair = ">=5.4.0"
vegafusion = {version = ">=1.5.0", extras = ["embed"]}
optuna = "^4.0.0"
lightgbm = "^4.5.0"
seaborn = "^0.13.2"
lightning = "^2.5.0.post0"

mkdocs = "^1.6.1"
mkdocs-material = "^9.6.1"
mkdocstrings = {extras = ["python"], version = "^0.27.0"}
mkdocs-gen-files = "^0.5.0"
xgboost = "^2.1.4"
dowhy = "^0.12"
pyreadstat = "^1.2.8"
polars = "^1.35.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
jupyterlab = "^4.1.1"
pytest = "^9.0.1"



[tool.poetry.group.docs.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
skcausal = "skcausal.cli.main:cli"