project:
  type: website

website:
  title: "skcausal"
  search:
    location: navbar
    limit: 5
    type: textbox
  navbar:
    search: true
    left:
      - href: getting-started.qmd
        text: "Getting Started"
      - href: examples.qmd
        text: "Examples"

format:
  html:
    mermaid:
      theme: neutral
    toc: true
    toc-expand: true
    theme:
      - cosmo
      - brand



