project:
  type: website

website:
  title: "skcausal"
  search:
    location: navbar
    limit: 5
    type: textbox
  navbar:
    search: true
    left:
      - href: examples/dose_response_curve.qmd
        text: "Example"

format:
  html:
    mermaid:
      theme: neutral
    toc: true
    toc-expand: true
    theme:
      - cosmo
      - brand



